version: "3"

services:
  backend:
    image: ghcr.io/discord-docs/backend
    env_file: "./env"
    restart: unless-stopped

  frontend:
    image: ghcr.io/discord-docs/frontend
    restart: unless-stopped

  #postgres:
  #  image: postgres:14-alpine
  #  environment:
  #    - POSTGRES_PASSWORD=postgres
  #  volumes:
  #    - "./data/postgres:/var/lib/postgresql/data"
  #  labels:
  #    com.centurylinklabs.watchtower.enable: false
  #  restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    env_file: "./env"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  caddy:
    image: caddy
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile"
      - "./data/caddy:/data"
    ports:
      - 80:80
      - 443:443